---
title: "Lecture 1: Welcome and Intro to R"
subtitle: "STAT 545 - Fall 2025"
format: 
  live-revealjs:
    scrollable: true
    slide-number: true
    smaller: true
    menu: 
      side: right
      width: wide
webr:
  packages:
    - dplyr
    - tidyverse
    - knitr
    - RColorBrewer
    - ggplot2
  persist: true
editor: visual
execute:
  echo: true
  warning: false
engine: webr
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}


## Welcome to STAT545!

For today's lecture, we are going to go through the some important information related to the course and jump right into some coding in R using an interactive worksheet and Jupyter Notebooks.


## Hello!

-  My name is Grace (she/her)

-  I'm an Assistant Professor of Teaching (just finished my first year)

-  Originally from NS ➡️ did Grad School in Waterloo, ON ➡️ now in Vancouver!

    -  Training: BSc Math, MMATH Biostatistics, PhD Biostatistics

-  Hobbies include crafting (knitting/crochet/pottery) and looking for banana slugs in the forest


## Positionality Statement 

We acknowledge that the land on which we gather is the traditional, ancestral, and unceded territory of the xwməθkwəy̓əm (Musqueam) People.\

Throughout this course, we will be weaving Indigenous topics into more "traditional" course material. I myself am a settler and am new to some of these topics. I am grateful for the opportunity to learn and grow with you.

## Classroom Policy

As stated in the syllabus, there is a **zero tolerance policy for disrespectful behaviour in this classroom**.

-   This includes within physical the classroom community (your peers, TAs, instructors, support staff) and online (discussion forums, social media).\

Some sensitive topics will be discussed throughout this course.

-   We are all learners and it is okay to make mistakes.

-   We will offer each other corrections politely, and I ask that you keep an open mind as we all continue to learn in this space.

This classroom is a safe space. [**You are welcome here.**]{.underline}


## Course Platforms

We will be using various technologies throughout this course which you should familiarize yourself with. The main platforms we'll be using are;

-   The course website (this one!),

-   Canvas (for submitting assignments),

-   Slack (for communications),

-   RStudio (for writing R code) [(](https://www.youtube.com/watch?v=dC2bRweVePo)[Video Here!](https://youtu.be/OYxDwybdlkY)[!)](https://www.youtube.com/watch?v=dC2bRweVePo),

-   GitHub (for version control and collaboration), and

-   Jupyter notebooks (for interactive worksheets) [(Video Here!)](https://youtu.be/CdISUthp8dk).

If you've never used some of these before, that's absolutely OK. This course is made to guide you through the basics of many of these platforms.

## Important Course Information

All of the important information is in the [syllabus](../../syllabus/syllabusA.qmd). There are a few items I'd like to emphasize:

-   STAT 545 has frequent worksheets. They are meant to supplement lectures.

-   STAT 545 A has a mini data analysis and collaborative project worth most of your marks. These are not graded on the basis of how sophisticated your statistical analysis is, but on the quality of your code and workflow. A grading rubric will be posted for each.

-   Stay home if you're sick. Fill out an Academic Concession Self Declaration form if you miss an assessment due to illness. Accommodations will be given on a case-by-case basis.

-   Bring a charged laptop to class!

-   All communications are to be done on Slack - do not email me questions unless they are of a sensitive nature (i.e., an academic concession form).


But please - read the syllabus :)

## Course AI Policy 


::: {.callout-important}
Plagiarism includes submitting the same response as another student, copying without citation, or copying from generative AI (ChatGPT, Gemini, etc.). Students are responsible for ensuring that any work submitted does not constitute plagiarism. Students who are in any doubt as to what constitutes plagiarism should consult their instructor before handing in any assignments.

In this course, Generative AI can be used in the following ways:

-   to clarify concepts discussed in class

-   as an "advanced search engine" (i.e., searching error codes)

-   debugging code that students wrote and attempted to debug on their own

Generative AI **CANNOT** be used to generate text or code from scratch. Assessments suspected of having AI-generated text and/or code will be flagged and temporarily assigned a grade of zero. Students will be required to meet with the instructor to receive a grade.

**Any use of Generative AI must be disclosed. Students will be asked to submit an AI Declaration Statement disclosing their use on any assessments**

:::



## Lecture Flow

-  Lectures for STAT545 are designed to be more interactive than a traditional statistics lecture. 

-  The class will begin with a short summary of the previous class, followed by an introduction to that day's topic. For most of the lectures, we will be going through the interactive worksheets (yes, the ones that you receive marks for and yes, prior to the deadline). This will give provide you with dedicated time to work on the assessments in class with access to the instructor and the TAs.

-  Many lectures will have an accompanying video, which will be linked on the webpage and on [our STAT545 YouTube Playlist.](https://youtube.com/playlist?list=PL32xpGMCWJAkihtosNGDQz0NP4UBqQnq8&si=sT-h1q8rTTKxs4vg)

-  Lectures build on top of each other and it is crucial to stay on track as we progress through this course.


# Intro to R

## To Save These Slides With Your Code

To Print to PDF (with your code!), do the following:

-   Open the in-browser print dialog `CMD/CTRL + P` or Right click \> Print

-   Change the Destination setting to Save as PDF.

-   Change the Layout to Landscape.

-   Change the Margins to None. Enable the Background graphics option.

-   Click Save 🎉

In all cases, ensure the code chunks don't get cut off (i.e., a line is too long). You will **not** be able to edit these from the PDF directly (though you could open the slides again and copy-and-paste to re-run the code!)
