project:
  type: website
  output-dir: docs

website:
  title: "STAT545 @ UBC"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - sidebar:syllabus
      - sidebar:lecturesi
      - sidebar:lecturesii
      - href: webpages/worksheets.qmd
        text: "Worksheets"
      - sidebar:collabproj
      - sidebar:mda
      - sidebar:casestudies
      - href: webpages/faq.qmd
        text: "FAQ"
        
  sidebar:
    - id: syllabus
      title: "Syllabus"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/syllabus/syllabusA.qmd
        - webpages/syllabus/syllabusB.qmd
        
    - id: lecturesi
      title: "Lectures: Part I"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/lectures_i/lec1a_installation.qmd
        - webpages/lectures_i/lec1b_introR.qmd
        - webpages/lectures_i/lec2A_reproducibility.qmd
        - webpages/lectures_i/lec2b_versioncontrol.qmd
        - webpages/lectures_i/lec3_dplyr.qmd
        - webpages/lectures_i/lec4_datavis.qmd
        - webpages/lectures_i/lec5_tidydata.qmd
        - webpages/lectures_i/lec6a_modelfitting.qmd
        - webpages/lectures_i/lec6b_dates.qmd
        - webpages/lectures_i/lec7a_readwritedata.qmd
        - webpages/lectures_i/lec7b_joiningtibbles.qmd
        
    - id: lecturesii
      title: "Lectures: Part II"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/lectures_ii/lec8a_functions.qmd
        - webpages/lectures_ii/lec8b_advfunctions.qmd
        - webpages/lectures_ii/lec9_rpackages.qmd


        
        

        
    - id: collabproj
      title: "Collaborative Project"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/collabproj/collabproj_deliverable1.qmd
        - webpages/collabproj/collabproj_deliverable2.qmd
                
    - id: mda
      title: "Mini Data Analysis"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/mda/mda_deliverable1.qmd
        - webpages/mda/mda_deliverable2.qmd      
   
    - id: casestudies
      title: "Case Studies"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/casestudies/fev_datamanipulation.qmd
        - webpages/casestudies/fev_datavis.qmd
        - webpages/casestudies/nycflights_dates.qmd
  
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



