project:
  type: website
  output-dir: docs

website:
  title: "STAT545 @ UBC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - teachingteam.qmd
      - material.qmd
      - worksheets.qmd
      - faq.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



