project:
  type: website
  output-dir: docs

website:
  title: "STAT545 @ UBC"
  navbar:
    background: primary
    search: true
    left:
      - href: webpages/index.qmd
        text: "Home"
      - sidebar:syllabus
      - sidebar:lectures
      - href: webpages/worksheets.qmd
        text: "Worksheets"
      - sidebar:collabproj
      - sidebar:mda
      - href: webpages/faq.qmd
        text: "FAQ"
        
  sidebar:
    - id: syllabus
      title: "Syllabus"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/syllabus/syllabusA.qmd
        - webpages/syllabus/syllabusB.qmd
        
    - id: lectures
      title: "Lectures"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/lectures/lec1a_installation.qmd
        - webpages/lectures/lec1b_introR.qmd
        - webpages/lectures/lec2A_reproducibility.qmd
        - webpages/lectures/lec2b_versioncontrol.qmd
        - webpages/lectures/lec3_dplyr.qmd
        - webpages/lectures/lec4_datavis.qmd
        - webpages/lectures/lec5_tidydata.qmd
        - webpages/lectures/lec6a_modelfitting.qmd
        - webpages/lectures/lec6b_dates.qmd
        - webpages/lectures/lec7_rrdata_tibble.qmd
        

        
    - id: collabproj
      title: "Collaborative Project"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/collabproj/collabproj_deliverable1.qmd
        - webpages/collabproj/collabproj_deliverable2.qmd
                
    - id: mda
      title: "Mini Data Analysis"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/mda/mda_deliverable1.qmd
        - webpages/mda/mda_deliverable2.qmd        
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



