project:
  type: website
  output-dir: docs

website:
  title: "STAT545 @ UBC"
  navbar:
    background: primary
    search: true
    left:
      - href: webpages/index.qmd
        text: "Home"
      - sidebar:syllabus
      - href: webpages/teachingteam.qmd
        text: "Teaching Team"
      - href: webpages/worksheets.qmd
        text: "Worksheets"
      - sidebar:lectures
      - href: webpages/faq.qmd
        text: "FAQ"
        
  sidebar:
    - id: syllabus
      title: "Syllabus"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/syllabus/syllabusA.qmd
        - webpages/syllabus/syllabusB.qmd
        
    - id: lectures
      title: "Course Material"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/lectures/lec0installation.qmd
        - webpages/lectures/lec1introR.qmd
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



