---
title: "Syllabus"
date-modified: last-modified
---

### Acknowledgement

UBC’s Point Grey Campus is located on the traditional, ancestral, and unceded territory of the xwməθkwəyəm (Musqueam) people. The land it is situated on has always been a place of learning for the Musqueam people, who for millennia have passed on their culture, history, and traditions from one generation to the next on this site.

### Course Information

|  |  |  |
|----|----|----|
| **Course Title** | **Course Code Number** | **Credit** **Value** |
| Exploratory Data Analysis Part I | STAT 545A | 1.5 |
| Exploratory Data Analysis | STAT 545B | 1.5 |

### Prerequisites

While there are no formal pre-requisites for STAT 545A, students should be familiar with basic statistical analyses and have taken at least one introductory statistics course.

STAT545A is a pre-requisite for STAT545B. No exceptions.

### Contact and Office Hours

| Instructor     | Contact Details    | Office Location | Office Hours |
|----------------|--------------------|-----------------|--------------|
| Grace Tompkins | grace\@stat.ubc.ca | ESB 3134        | TBD          |

| Teaching Assistants |
|---------------------|
| TBD                 |
| TBD                 |
| TBD                 |

### Course Structure

This course will feature short lectures and in-class demonstrations so students get hands-on experience with the help of their instructor and TAs. The class will be partially "flipped", with students being expected to review a short video prior to the lecture. Dedicated time will be given in lecture for students to work through assigned worksheets.

### Schedule of Topics and Assessments

**PART A:**

+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Date             | Topic                                  | In-class work                         | Assessments                                     |
+==================+========================================+=======================================+=================================================+
| Tuesday Sept 2   | Installation                           |                                       |                                                 |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Thursday Sept 4  | Intro to STAT545 and R                 | Worksheet A1                          | **Worksheet A1 due September 8th, 11:59pm PT**  |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Tuesday Sept 9   | Authoring and Reproducibility          |                                       |                                                 |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Thursday Sept 11 | Version Control                        |                                       |                                                 |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Tuesday Sept 16  | Data Manipulation with dplyr           | Worksheet A2                          |                                                 |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Thursday Sept 18 |                                        | Worksheet A2                          | **Worksheet A2 due September 22nd, 11:59pm PT** |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Tuesday Sept 23  | Data Visualization                     | Worksheet A3                          |                                                 |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Thursday Sept 25 |                                        | Worksheet A3                          | **Worksheet A3 due September 29th, 11:59pm PT** |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Tuesday Sept 30  | Tidy Data                              | Worksheet A4                          |                                                 |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Thursday Oct 2   |                                        | Worksheet A4                          |                                                 |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Tuesday Oct 7    | Model Fitting                          | Worksheet A4                          | **Worksheet A4 due October 13th, 11:59pm PT**   |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Thursday Oct 9   | Factors and Dates                      | Worksheet A5                          |                                                 |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Tuesday Oct 14   | Reading and Writing Data, Tibble Joins | Worksheet A5                          |                                                 |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+
| Tuesday Oct 16   | Review and Work Session                | Worksheet 5, Mini Data Analysis (MDA) | **Worksheet A5 due October 20th, 11:59pm PT**   |
+------------------+----------------------------------------+---------------------------------------+-------------------------------------------------+

**PART B:**

| Date | Topic | In-class Work | Assessments |
|------|-------|---------------|-------------|
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
|      |       |               |             |
