---
title: "Mini Data Analysis: Deliverable 1"
date-modified: last-modified
---

## Deliverable 1 will be due on Friday October 13th, 2026 at 11:59pm PT.

This project includes two deliverables, each with explicit tasks. 

Each deliverable will be also graded for reproducibility, cleanliness, and coherence of the overall Github submission. While the two deliverables will be submitted as independent assessments, the analysis itself is a continuum - think of it as two chapters to a story. Each chapter, or in this case, portion of your analysis, should be easily followed through by someone unfamiliar with the content. [Here](https://swcarpentry.github.io/r-novice-inflammation/06-best-practices-R.html) is a good resource for what constitutes "good code". Learning good coding practices early in your career will save you hassle later on!



# Instructions

### Create a Copy of the GitHub Repository Template

You will begin by creating a copy of this template repository within our STAT545 organization. 

-  Use the following naming convention for your repository: `mda-firstname-lastname`

-  Set the owner as `UBC-STAT545-F2026`

Next, clone the repository so you can access it on your local machine! 

### Complete the Assignment

You will be working on the `mda-deliverable1.Rmd` file for this assessment.

Fill in the sections that are tagged with `<!--- start your work below --->`.

<!---
To complete this deliverable, download the template below:

<div style="text-align: center;">

```{r}
#| echo: false

library(downloadthis)
download_file(path = "mdatemplates/mda_deliverable1.Rmd",
              output_name = "mda_deliverable1",
              output_extension = ".Rmd",
              button_label = "Download .Rmd Template",
              button_type = "primary",
              has_icon = TRUE,
              icon = "fa fa-save")  
```

</div>

<br>


--->

