---
title: "Syllabus: STAT 545 A (Part I)"
subtitle: "Sept 7 2026 to October 23 2026"
date-modified: last-modified
format:
  html: default
  pdf: default
---

:::{.callout-important}
Please see [the academic integrity section](#academic-integrity) for this course's AI policy.
:::

\vspace{1cm}

UBC’s Point Grey Campus is located on the traditional, ancestral, and unceded territory of the xwməθkwəyəm (Musqueam) people. The land it is situated on has always been a place of learning for the Musqueam people, who for millennia have passed on their culture, history, and traditions from one generation to the next on this site.

### Course Information

| **Course Title** | **Course Code** | **Credit** **Value** | **Class Times** | **Class Location** |
|---------------|---------------|---------------|---------------|---------------|
| Exploratory Data Analysis Part I | STAT 545 A | 1.5 | Tues/Thurs: 9:00am - 10:20am | See Workday |
: {.hover}

### Prerequisites

While there are no formal pre-requisites for STAT 545 A, students should be familiar with basic statistical analyses and have taken at least one introductory statistics course.

STAT545 A is a pre-requisite for STAT545 B. No exceptions.

### Contact and Office Hours

| Instructor     | Contact Details        | Office Location | Office Hours |
|----------------|----------------------|-------------|--------------|
| [Dr. Grace Tompkins](https://grcetmpk.github.io/) | grace\<at\>stat.ubc.ca | ESB 3134        |              |
: {.hover}

| Teaching Assistants (TAs) | Office Hours | Location |
|---------------------------|--------------|----------|
: {.hover}

### Course Structure

This course will feature short lectures and in-class demonstrations so students get hands-on experience with the help of their instructor and TAs. Dedicated time will be given in lecture for students to work through assigned worksheets and projects.

**Please bring a charged laptop to every class.** If you do not have a personal laptop, one can be borrowed through the [UBC library](https://wiki.ubc.ca/Library:Technology_Borrowing/Laptop_Lending).

### Schedule of Topics

See schedule and tentative due dates [here](https://ubc-stat.github.io/stat545/webpages/lectures.html).

### Assessments

This course will have autograded, formative worksheets meant to guide you through a number of exercises.

| Assessment | Percent Grade | Note |
|--------------|----------|------------------------|
|Worksheets | 20% | Five guided worksheets |
| Collaborative Project | 35% | Team project intended for practicing version control and collaboration |
| Mini Data Analysis  | 45% | Students write their own mini analysis |
: {.hover}

#### Worksheets

Worksheets are interactive assignments that allow students to get real-time feedback on their code. Your grade will be based on the number of correct answers provided. There are unlimited attempts for the worksheets, and time will be given in class to work through them. Each worksheet is worth 4% of your final grade.

Worksheets are produced with Jupyter Notebooks, and will be submitted on Canvas.


#### Collaborative Project

Students will practice using Version Control and collaborative tools on Github, troubleshoot broken R code, and rewrite code to address issues. Teams will be randomly assigned.


#### Mini Data Analysis

Students will become more familiar with R and generate a reproducible report using RMarkdown and various packages, such as `tibble`. This analysis is done individually. There are two equally weighted deliverables.


### Auditing Students

Auditing students are required to pass all assessments (assignments and worksheets). All assessments are graded on a pass/fail basis for those officially auditing.

You must be registered as an auditing student to attend lectures due to capacity limitations.

### Course Communications

We will be using Slack as our primary platform of all course-related communications! Students will be emailed an invite to their class' Slack workspace.

Official course communications will occur on the `#announcements` channel. You will receive an invite on the first day of classes. Please notify the instructor by email if you have not received your personal invite.

Our STAT 545 team will be actively monitoring Slack during regular working hours (9am to 5pm PT, Monday to Friday). You are free to ask questions outside of this window but please keep in mind that there are no expectations for the team to answer questions outside of working hours or on weekends or holidays.

To make the most out of Slack, please

-   Use the `#general` channel for clarifications, asking about course organization, or clarifying instructions. Things you post on the `#general` channel will be seen by everyone, so please do not provide information that gives away answers to assignments.

-   Make a group chat with our TAs when you need more personalized help, or have an issue with grading. They may direct you to the `#general` channel when appropriate, or direct you to the instructor. **Do not direct message the instructor for questions related to the course content**.

-   Direct message the instructor if there is a concern that is more personal (i.e., you need to self declare an absence) or if you have already talked to the TAs about an issue and are unsatisfied. You can also direct message the instructor if you are having issues with a group member in any group-related assignments.

-   Post in the `#random` channel if you find things related to the course that you'd like to share

### Privacy

Slack and GitHub are hosted on servers stored outside of Canada. Please keep this in mind.

### Policies

#### Regrade Requests

Regrade requests must be sent to the TAs through Slack within one week of the assessment being returned. If required, regrade requests can be escalated to the instructor [only if]{.underline} the request has already been brought up to the TA team and the student is unsatisfied. The instructor reserves the right to regrade the entire assessment, resulting in a higher or lower mark than originally provided.

#### Late Policies

Worksheets (and larger assignments, if applicable) are due at 11:59pm PT on the date indicated in the course schedule. For a late submission, a 24 hour extension will be provided for the first offense. Late submissions will be given a grade of 0 for subsequent occurrences.

**Due to the pace of the course, no submissions will be accepted past 24 hours for assessments, including the mini data analysis and the collaborative project. If you are having issues with a team member regarding any group work, reach out to the instructor directly through Slack or email.**

#### Academic Concession

UBC no longer requires a doctor’s note (or supporting documentation) for [academic concession](http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,48,0,0). A self-declaration will suffice – [here is a template you can use](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://biologyprogram-2023.sites.olt.ubc.ca/files/2024/10/Academic-Concession-Form-2022W.pdf). The form is also posted on our website. Please submit this to the instructor via email.

Examples of “conflicting responsibility” are conference travel and time-sensitive field work.

### Academic Integrity {#academic-integrity}

Plagiarism includes submitting the same response as another student, copying without citation, or copying from generative AI (ChatGPT, Gemini, etc.). Students are responsible for ensuring that any work submitted does not constitute plagiarism. Students who are in any doubt as to what constitutes plagiarism should consult their instructor before handing in any assignments.

In this course, Generative AI can be used in the following ways:

-   to clarify concepts discussed in class

-   as an "advanced search engine" (i.e., searching error codes)

-   debugging code that students wrote and attempted to debug on their own

Generative AI **CANNOT** be used to generate text or code from scratch. Assessments suspected of having AI-generated text and/or code will be flagged and temporarily assigned a grade of zero. Students will be required to meet with the instructor to receive a grade.

**Any use of Generative AI must be disclosed. Students will be asked to submit an AI Declaration Statement disclosing their use on any assessments**

For more information see the [UBC Academic Misconduct policies](http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,54,111,959).

## Health and Support

-   **If you are sick:** Stay home. Access annotated slides on Canvas and use Piazza for discussion.
-   **Instructor health:** If the instructor is ill but well enough to teach, lectures will move to Zoom. If not well enough, a TA may take over or accommodations will be made.

### More UBC resources for student success

-   [Academic and learning resources](https://students.ubc.ca/enrolment/academic-learning-resources)

-   [Academic Concessions](https://students.ubc.ca/enrolment/academic-learning-resources/academic-concessions)

-   [Academic Honesty and Standards](https://vancouver.calendar.ubc.ca/campus-wide-policies-and-regulations/academic-honesty-and-standards)

-   [Attendance](https://vancouver.calendar.ubc.ca/campus-wide-policies-and-regulations/attendance)

-   [Student Conduct and Discipline](https://vancouver.calendar.ubc.ca/campus-wide-policies-and-regulations/student-conduct-and-discipline)

-   [Viewing Marked Work](https://vancouver.calendar.ubc.ca/campus-wide-policies-and-regulations/academic-assessment/viewing-marked-work)

### Copyright

Course materials are licensed under [Creative Commons 4.0](https://creativecommons.org/licenses/by/4.0/).
