---
title: "Frequently Asked Questions"
date-modified: last-modified
---

**Not finding what you're looking for? Try the search bar at the top right-hand side of this website!**

## I'm having issues enrolling - who do I contact about registration?

Please email [our Graduate Program Manager](https://www.stat.ubc.ca/users/mairead-roche). The instructor does not have any control over registration, nor any access to the registration system.

## When is the course offered?

September - December of each academic year. Typical format: STAT 545A 1.5 credits in September through mid October, followed by STAT 545B 1.5 credits from mid October through early December.


## I can only register for STAT545A on Workday, but not STAT545B! Am I doing something wrong?

No, since STAT545A is a prerequisite for STAT545B, you'll only be able to register for part B in October. Don't worry - there will still be space for you! 


## Why are there two courses, instead of a single “STAT 545” course?

For several years, Jenny Bryan taught STAT 545A as a 1.5 credit course. She – and many students – felt there was a lot of great, relevant content that could go into an additional 1.5 credits.

A full semester of data exploration, visualization, and all-around data wrangling was piloted in 2014/2015. It was structured as two half courses primarily so that several year’s worth of STAT 545A alums could register for the second part (then STAT 547M) and get the “missing half” of the course. And now it’s hard to break the cycle.

## I have taken STAT 545A for 1.5 credits in the past. Can I take STAT 545B?

YES. But STAT 545 keeps changing to keep current with the R world. It is your responsibility to level up.

## Can I just take the second half, i.e. STAT 545B?

NO, not unless you have taken STAT 545A previously.

## Can I just take the second half, i.e. STAT 545B? I’ll do a self-study for STAT 545A.

Unfortunately, the answer is still no. As much as we’d want to say yes to you, it just becomes too difficult for us to evaluate your level without having seen deliverables for STAT 545A.

## I am an undergraduate. Can I take this course?

Only in special circumstances. Contact an advisor.

## What if I’ve never had a stats class?

There are no official pre-requisites for STAT 545A but most students will have had at least one prior statistics course or comparable experience.

## I'm not enrolled – can I sit in during class?

Unfortunately not. The room is usually at capacity, and further, we’ve allocated TA time for the specific number of students attending the class.

## I’d like to officially audit – can I?

Absolutely! Please take a look at the syllabus to see what is required of auditors so that you have an understanding of your expectations coming into the course; then, fill out the form (graduate version) and send it to the instructor to get signed.

## The course is full – can I audit instead?

You’ll still have to join the waitlist – auditing still counts as a seat in the class, so auditing is not a way around the course capacity.

In all cases, I encourage you to register! Or if the course is full, join the waitlist. Alternatively, you can engage in your own self-study using our online resources.

## The course is full. Is there a chance that the course capacity will increase?

Unfortunately, the course enrollment capacity will not increase. But, I encourage you to join the waitlist.

## The course is listed as “restricted”. What should I do?

When all the open seats are taken, the course is listed as “restricted”, as the remaining seats can only be taken by students of specific types. If you are a student of that type, then go ahead and register through Workday! Otherwise, I encourage you to join the waitlist.

## Can I take this course if I'm not a Statistics student?

This course is designed for students outside of the Department of Statistics! All are welcome. 

## Do I need a computer?

YES. You absolutely must have access to a computer on which you can install software, download data, etc. In fact, class meetings will be a mix of lecture, discussion, and live coding. Students will get the most out of this if they can bring their own laptop to class every day. If this is not possible, we will try to help you work something out.

## Are they any prerequisites?

There are no official pre-requisites for STAT 545A, but most students will have had at least one prior statistics course or comparable experience.

STAT 545B requires STAT 545A.
