---
title: "STAT545 A/B: Exploratory Data Analysis (Fall 2025)"
date-modified: last-modified

---

Welcome to STAT 545 at the University of British Columbia! Whether you're a student enrolled in STAT 545 or simply someone looking to learn how to write reproducible and collaborative data analyses, it is our hope that this website will serve as a great resource for learning these new skills! 

In short, this course will enable you to confidently write clean and modern data analyses in R using version control software (GitHub), and creating reports using R Markdown. The primary focus will be on using these technologies to conduct analyses with daily workflow, rather than the statistical theory and methods for analysis. 

This course is divided into two parts. In Part I (STAT545 A), we will introduce

* R and RStudio,
* Report generation with R Markdown,
* Project organization, workflow, and coding style,
* Data management with dataframes and tibbles using tidyverse,
* Data visualization with ggplot2, and
* Version control using Git and Github.

In Part II (STAT545 B), we will dive deeper into

* Writing functions in R,
* Advanced computations on data,
* Functional programming with purrr,
* R packages,
* Interactive pages, apps, and graphics with RShiny, and
* Website development using Quarto.

**If you are a student enrolling in this course for credit at UBC, you MUST take STAT 545 A to enroll in STAT545 B. There are no exceptions to this rule.**

