---
title: "STAT545 A Schedule"
date-modified: last-modified
---

::: {.callout-note icon="false"}
## This Week at a Glance

**Lectures:**

-   Tuesday September 2: Get in-person help with installing course software

-   Thursday September 4th: Intro to R lecture, begin working through Worksheet A1

**Assessments Due This Week:**

-   Nothing! Ensure you have completed all installation instructions by next week!

**Upcoming Deadlines** - Nothing!
:::

## Lectures

+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| Week    | Date           | Topic                                                                                                                         | In-class work            |
+=========+================+===============================================================================================================================+==========================+
| 1       | Tues. Sept 2   | [Installation](../lectures_i/lec1a_installation.qmd)                                                                          | Install Software         |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         | Thurs. Sept 4  | [Intro to STAT545 and R](../lectures_i/lec1b_introR.qmd)                                                                      | Worksheet A1             |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         |                |                                                                                                                               |                          |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| 2       | Tues. Sept 9   | [Authoring and Reproducibility](../lectures_i/lec2A_reproducibility.qmd)                                                      |                          |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         | Thurs. Sept 11 | [Version Control](../lectures_i/lec2b_versioncontrol.qmd)                                                                     |                          |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         |                |                                                                                                                               |                          |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| 3       | Tues. Sept 16  | [Data Manipulation with `dplyr`](../lectures_i/lec3_dplyr.qmd)                                                                | Worksheet A2             |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         | Thurs. Sept 18 |                                                                                                                               | Worksheet A2             |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         |                |                                                                                                                               |                          |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| 4       | Tues.. Sept 23 | [Data Visualization](../lectures_i/lec4_datavis.qmd)                                                                          | Worksheet A3             |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         | Thurs. Sept 25 |                                                                                                                               | Worksheet A3             |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         |                |                                                                                                                               |                          |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| 5       | Tues. Sept 30  | **\*\*\* NO CLASS \*\*\***                                                                                                    |                          |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         | Thurs. Oct 2   | [Tidy Data](../lectures_i/lec5_tidydata.qmd)                                                                                  | Worksheet A4             |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         |                |                                                                                                                               |                          |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| 6       | Tues. Oct 7    | [Model Fitting](../lectures_i/lec6a_modelfitting.qmd)                                                                         | Worksheet A4             |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         | Thurs. Oct 9   | [Factors and Dates](../lectures_i/lec6b_dates.qmd)                                                                            | Worksheet A5             |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         |                |                                                                                                                               |                          |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| 7       | Tues. Oct 14   | [Reading and Writing Data](../lectures_i/lec7a_readwritedata.qmd), and [Tibble Joins](../lectures_i/lec7b_joiningtibbles.qmd) | Worksheet A5             |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|         | Thurs. Oct 16  | Review and Work Session                                                                                                       | Worksheet A5             |
|         |                |                                                                                                                               |                          |
|         |                |                                                                                                                               | Mini Data Analysis (MDA) |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+--------------------------+

This schedule is subject to change. Any changes will be announced via the `#annoucements` channel on Slack, and major changes will be sent out via email.

## Assessments

### Worksheets

| Worksheet    | Release Date         | Due Date (11:59PM PT) |
|--------------|----------------------|-----------------------|
| Worksheet A1 | September 2nd, 2025  | NA                    |
| Worksheet A2 | September 15th, 2025 | September 22nd, 2025  |
| Worksheet A3 | September 22nd, 2025 | September 29th, 2025  |
| Worksheet A4 | September 29th, 2025 | October 13th, 2025    |
| Worksheet A5 | October 13th, 2025   | October 20th, 2025    |

### Collaborative Project

+---------------------------------+---------------------+-----------------------+
| Collaborative Project Milestone | Release Date        | Due Date (11:59pm PT) |
+=================================+=====================+=======================+
| Deliverable 1 (100 points)      | September 4th, 2025 | September 19th, 2025  |
+---------------------------------+---------------------+-----------------------+
| Deliverable 2 (78 points)       | September 4th, 2025 | September 26th, 2025  |
+---------------------------------+---------------------+-----------------------+

### Mini Data Analysis

+------------------------------+----------------------+-----------------------+
| Mini Data Analysis Milestone | Release Date         | Due Date (11:59PM PT) |
+==============================+======================+=======================+
| Deliverable 1 (36 points)    | September 26th, 2025 | October 3rd, 2025     |
+------------------------------+----------------------+-----------------------+
| Deliverable 2 (36 points)    | September 26th, 2025 | October 22nd, 2025    |
+------------------------------+----------------------+-----------------------+

**See the [Syllabus](../syllabus/syllabusA.qmd) for more information.**
