---
title: "Assignments (Part A)"
format: html
---

The major assignments for STAT545 A include a collaborative project and mini data analysis. The links to these projects will be released on the indicated date, and can be found on this page.

## Collaborative Project

The purpose of this project is to allow students to gain confidence using collaborative version control tools, such as Git and GitHub. Groups will be randomly assigned by the instructor. There is one deliverable.

| Deliverable           | Release Date            | Due Date               |
|-----------------------|-------------------------|------------------------|
| Collaborative Project | Tues September 22, 2026 | Thurs October 01, 2026 |

## Mini Data Analysis

In this two-part assignment, students will become more familiar with R and generate a reproducible report using RMarkdown and various packages, such as `ggplot2`. This analysis is done individually. There are two equally weighted deliverables.

| Deliverable | Release Date | Due Date |
|--------------------------|-----------------------|-----------------------|
| Mini Data Analysis - Milestone 1 | Thurs October 01, 2026 | Tues October 13, 2026 |
| Mini Data Analysis - Milestone 2 | Thurs October 01, 2026 | Tues October 27, 2026 |


## Generative AI Disclosure

In this course, Generative AI can be used in the following ways:

-   to clarify concepts discussed in class

-   as an "advanced search engine" (i.e., searching error codes)

-   debugging code that students wrote and attempted to debug on their own

Generative AI **CANNOT** be used to generate text or code (including comments) from scratch. 

Any use of Generative AI must be disclosed. 

**To disclose your use, please copy and paste the following template into the README of your GitHub Repository and fill out the relevant details** [in square brackkets]. BE SPECIFIC. Saying you used it to debug your code is not enough. Explicitly describe where you got stuck 

Here is an example of a specific, explicit debug: 

> "I had the error `attempt to apply non-function` after running my code. I used Claude to help me identify that this error was due to me attempting to multiply two numbers together without the use of a `*`, i.e. `(2)(3)` instead of `2*3`." 

```markdown

## Generative AI Statement 

Generative AI (through [LIST MODELS USED, i.e. ChatGPT, CoPilot)] was used to 
help me complete  this assignment in the following ways. 

1. [Describe here]

2. [Describe here]

...

I affirm that Generative AI was not used to generate text, code, or comments for 
my assessments. 
```

If you did not use Generative AI, you do not need to include this in the README. 

Assessments suspected of having AI-generated text and/or code, or assignments where the Generative AI use was not disclosed, will be flagged and temporarily assigned a grade of zero. Students will be required to meet with the instructor to receive a grade.
