---
title: "Mini Data Analysis: Deliverable 2"
date-modified: last-modified
---
## Deliverable 2 will be due on October 27nd, 2026 at 11:59pm PT



:::{.callout-warning}

In this course, Generative AI can be used in the following ways:

-   to clarify concepts discussed in class

-   as an "advanced search engine" (i.e., searching error codes)

-   debugging code that students wrote and attempted to debug on their own

Generative AI **CANNOT** be used to generate text or code (including comments) from scratch. 

Any use of Generative AI must be disclosed. 

**To disclose your use, please copy and paste the following template into the README of your GitHub Repository and fill out the relevant details** [in square brackets]. BE SPECIFIC. Saying you used it to debug your code is not enough. Explicitly describe where you got stuck 

Here is an example of a specific, explicit debug: 

> "I had the error `attempt to apply non-function` after running my code. I used Claude to help me identify that this error was due to me attempting to multiply two numbers together without the use of a `*`, i.e. `(2)(3)` instead of `2*3`." 

```markdown

## Generative AI Statement 

Generative AI (through [LIST MODELS USED, i.e. ChatGPT, CoPilot)] was used to 
help me complete  this assignment in the following ways. 

1. [Describe here]

2. [Describe here]

...

I affirm that Generative AI was not used to generate text, code, or comments for 
my assessments. 
```

If you did not use Generative AI, please include the following in your README:

```markdown

## Generative AI Statement 

Generative AI was not used in any way throughout this assignment.

```


Assessments suspected of having AI-generated text and/or code, or assignments where the Generative AI use was not disclosed, will be flagged and temporarily assigned a grade of zero. Students will be required to meet with the instructor to receive a grade.


**Fill out Task 3.4 as you go through your assignment if you do opt to use Generative AI.**

:::



Download the following file and add it to your Mini Data Analysis Repository (the same one you used for Deliverable 1). Follow the directions in the file!


<div style="text-align: center;">

```{r}
#| echo: false

library(downloadthis)
download_file(path = "mdafiles/mda_deliverable2.Rmd",
              output_name = "mda_deliverable2",
              output_extension = ".Rmd",
              button_label = "Download .Rmd File",
              button_type = "primary",
              has_icon = TRUE,
              icon = "fa fa-save")  
```

</div>

<br>

