---
title: "Worksheets"
date-modified: last-modified
---

Worksheets are guided exercises that are meant to supplement lectures, and will be graded as part of your final mark in STAT545. Time will be given in lecture to work on these formative assessments.

Worksheets are produced with Jupyter Notebooks. For installation instructions, see [Lecture 1A (Installation)](../lectures_i/lec1a_installation.qmd) or check out [this YouTube video](https://www.youtube.com/watch?v=CdISUthp8dk) (**ignore the instructions for downloading from GitHub! You can now download directly by clicking the Worksheet name below**). 


:::{.callout-note}

When submitting to Canvas, **please keep the original file name** (i.e., "worksheet_a01.ipynb"). If you change the file name, your sheet will not work with the auto-grading system! Do not use names like "worksheet_a01 (1).ipynb" or "worksheet_a01_grace.ipynb". 

:::



### **STAT 545 A**

| Worksheet | Release Date | Due Date (11:59PM PT) |
|------------------------|------------------------|------------------------|
| <a href="worksheets_blank/worksheet_a01.ipynb" download>Worksheet A1</a> | September 8th, 2026 | September 15th, 2026 |
| Worksheet A2 | September 15th, 2026 | September 22nd, 2026 |
| Worksheet A3 | September 29th, 2026 | October 6th, 2026 |
| Worksheet A4 | October 6th, 2026 | October 15th, 2026 |
| Worksheet A5 | October 15th, 2026 | October 22nd, 2026 |


### **STAT 545 B:**

| Worksheet    | Release Date | Due Date (11:59PM PT) |
|--------------|--------------|-----------------------|
| Worksheet B1 | Oct 27, 2026 | Nov 3, 2026           |
| Worksheet B2 | Nov 12, 2026 | Nov 19, 2026          |
| Worksheet B3 | Nov 24, 2026 | Dec 3, 2026           |

[**Worksheet Tips and Tricks:**]{.underline}

-   Only edit cells where prompted. If you accidentally click on a text-only cell, hit the play button and it should re-render.

-   You can check your answers prior to submitting! If you see a "Success!" message, you got the question right. Otherwise, a detailed error message will help you diagnose what went wrong.

-   Save your work frequently.

-   Prior to submitting, restart your kernel and run all to ensure that no errors persist. Save again.

-   Submit the .ipynb file to Canvas with the file name "worksheet_a##".

-   We're here to help along the way on Slack, so don't be shy to ask for help if you need it.
